trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

variables:
  terraformVersion: '1.5.0'  # Specify your Terraform version
  backendStorageAccount: 'mystorageaccount'
  backendContainerName: 'terraform-state'
  backendKey: 'terraform.tfstate'
  location: 'East US'

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Install Terraform
- task: UseTerraform@0
  inputs:
    terraformVersion: $(terraformVersion)

# Step 2: Initialize Terraform
- script: |
    terraform init \
      -backend-config="storage_account_name=$(backendStorageAccount)" \
      -backend-config="container_name=$(backendContainerName)" \
      -backend-config="key=$(backendKey)"
  displayName: 'Terraform Init'

# Step 3: Plan Terraform Changes
- script: |
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

# Step 4: Apply Terraform Changes
- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
